name: TDD CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner for iOS builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the app
        run: xcodebuild clean build -project TDD.xcodeproj -scheme TDD -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5'

      - name: Test the app
        run: xcodebuild clean test -project TDD.xcodeproj -scheme TDD -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' ONLY_ACTIVE_ARCH=YES
